input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics            => ["metrics"]
    codec             => "json"
    auto_offset_reset => "earliest"
  }
}

filter {
  date {
    match => ["@timestamp", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    convert => {
      "cpu_percent"    => "float"
      "memory_percent" => "float"
      "latency_ms"     => "float"
      "request_count"  => "integer"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "metrics-%{+YYYY.MM.dd}"
    data_stream => "true"
    data_stream_type => "metrics"
    data_stream_dataset => "hosts"
    data_stream_namespace => "default"
  }
}